import json
from pathlib import Path
from apps.api.app.schemas.render_spec import StyleCategory, CaptionRenderSpec, StyleTemplate

TEMPLATES = [
    # ==================== VIRAL_BOLD (10) ====================
    {
        "id": "viral-hormozi",
        "name": "Hormozi Punch",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Aggressive, high-energy uppercase bold text with punchy word pop and vibrant yellow highlight.",
        "tags": ["viral", "hormozi", "bold", "punchy", "high-retention"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 46,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFE600",
            "strokeColor": "#000000",
            "strokeWidth": 7.0,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 10.0,
            "positionY": 75.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 100, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#000000", "color": "#FFE600", "borderColor": "#FFE600"}
    },
    {
        "id": "viral-mrbeast",
        "name": "MrBeast Hype",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Massive display typography with vibrant cyan highlight, heavy outline, and bounce animation.",
        "tags": ["mrbeast", "bold", "cyan", "outline", "youtube"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 48,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#00F0FF",
            "strokeColor": "#000000",
            "strokeWidth": 8.0,
            "shadowColor": "rgba(0,0,0,0.95)",
            "shadowBlur": 12.0,
            "positionY": 72.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "bounce", "durationMs": 140, "scale": 1.25}
        },
        "thumbnailCss": {"background": "#0F172A", "color": "#00F0FF", "borderColor": "#00F0FF"}
    },
    {
        "id": "viral-iman",
        "name": "Iman Luxury",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Polished high-end typography with rich metallic gold accent and swift zoom animation.",
        "tags": ["iman", "luxury", "gold", "clean", "aesthetic"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 40,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFD700",
            "strokeColor": "#1A1A1A",
            "strokeWidth": 4.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 8.0,
            "positionY": 78.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "zoom", "durationMs": 120, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#18181B", "color": "#FFD700", "borderColor": "#FFD700"}
    },
    {
        "id": "viral-ali-abdaal",
        "name": "Ali Clean High",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Readable modern sans with subtle warm yellow marker highlight.",
        "tags": ["ali", "clean", "minimal", "productivity", "warm"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 38,
            "fontWeight": "700",
            "textTransform": "none",
            "textColor": "#F8FAFC",
            "highlightColor": "#FDE047",
            "strokeColor": "#0F172A",
            "strokeWidth": 3.0,
            "shadowColor": "rgba(0,0,0,0.6)",
            "shadowBlur": 6.0,
            "positionY": 80.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.12}
        },
        "thumbnailCss": {"background": "#1E293B", "color": "#FDE047", "borderColor": "#FDE047"}
    },
    {
        "id": "viral-neon-punch",
        "name": "Neon Toxic Punch",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Electrifying toxic green font with deep black drop shadow and elastic snap.",
        "tags": ["neon", "toxic", "green", "punch", "gamer"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 44,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#39FF14",
            "strokeColor": "#000000",
            "strokeWidth": 7.0,
            "shadowColor": "rgba(57,255,20,0.5)",
            "shadowBlur": 16.0,
            "positionY": 75.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "elastic", "durationMs": 130, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#052E16", "color": "#39FF14", "borderColor": "#39FF14"}
    },
    {
        "id": "viral-crimson-hype",
        "name": "Crimson Hype",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "High contrast aggressive red styling with thick black stroke and dynamic bounce.",
        "tags": ["crimson", "red", "hype", "high-contrast"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 46,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF2A2A",
            "strokeColor": "#000000",
            "strokeWidth": 7.5,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 8.0,
            "positionY": 74.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "bounce", "durationMs": 120, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#450A0A", "color": "#FF2A2A", "borderColor": "#FF2A2A"}
    },
    {
        "id": "viral-midnight-gold",
        "name": "Midnight Gold",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Refined serif authority with deep obsidian backdrop and radiant gold active words.",
        "tags": ["gold", "midnight", "classy", "authority"],
        "renderSpec": {
            "fontFamily": "Georgia",
            "fontSize": 40,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FDFBF7",
            "highlightColor": "#D4AF37",
            "strokeColor": "#09090B",
            "strokeWidth": 4.0,
            "shadowColor": "rgba(0,0,0,0.85)",
            "shadowBlur": 10.0,
            "positionY": 78.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 100, "scale": 1.1}
        },
        "thumbnailCss": {"background": "#09090B", "color": "#D4AF37", "borderColor": "#D4AF37"}
    },
    {
        "id": "viral-alpha-impact",
        "name": "Alpha Stomp",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Heavy stomping impact typeface with vivid hot magenta accent.",
        "tags": ["alpha", "stomp", "impact", "magenta"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 50,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF0055",
            "strokeColor": "#000000",
            "strokeWidth": 8.0,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 10.0,
            "positionY": 70.0,
            "maxWordsPerLine": 2,
            "displayMode": "chunk",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.25}
        },
        "thumbnailCss": {"background": "#2E0214", "color": "#FF0055", "borderColor": "#FF0055"}
    },
    {
        "id": "viral-speed-runner",
        "name": "Speed Runner",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Italicized high-velocity text with rapid slide animations.",
        "tags": ["speed", "italic", "velocity", "sports"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 42,
            "fontWeight": "800",
            "fontStyle": "italic",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#00D2FF",
            "strokeColor": "#001026",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 8.0,
            "positionY": 76.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "slide", "durationMs": 100, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#082F49", "color": "#00D2FF", "borderColor": "#00D2FF"}
    },
    {
        "id": "viral-volkov-glow",
        "name": "Volkov Violet",
        "category": StyleCategory.VIRAL_BOLD,
        "description": "Electric violet cyberpunk mood with glowing outline.",
        "tags": ["volkov", "violet", "cyberpunk", "glow"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 44,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#B026FF",
            "strokeColor": "#1E0038",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(176,38,255,0.7)",
            "shadowBlur": 18.0,
            "positionY": 75.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 115, "scale": 1.18}
        },
        "thumbnailCss": {"background": "#2E1065", "color": "#B026FF", "borderColor": "#B026FF"}
    },

    # ==================== MINIMAL (10) ====================
    {
        "id": "minimal-modern-clean",
        "name": "Modern Pristine",
        "category": StyleCategory.MINIMAL,
        "description": "Flawless neutral sans typography with a soft drop shadow. Zero clutter.",
        "tags": ["minimal", "clean", "modern", "subtle"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFFFFF",
            "strokeColor": "#000000",
            "strokeWidth": 2.0,
            "shadowColor": "rgba(0,0,0,0.6)",
            "shadowBlur": 6.0,
            "positionY": 82.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 90, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#18181B", "color": "#FFFFFF", "borderColor": "#3F3F46"}
    },
    {
        "id": "minimal-slate-subtitle",
        "name": "Slate Pill Subtitle",
        "category": StyleCategory.MINIMAL,
        "description": "Translucent dark pill container guaranteeing maximum readability over any background.",
        "tags": ["slate", "box", "pill", "readable"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 32,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#F1F5F9",
            "highlightColor": "#F1F5F9",
            "strokeColor": "transparent",
            "strokeWidth": 0.0,
            "shadowColor": "transparent",
            "shadowBlur": 0.0,
            "backgroundColor": "rgba(15, 23, 42, 0.75)",
            "backgroundPaddingX": 18.0,
            "backgroundPaddingY": 8.0,
            "backgroundBorderRadius": 8.0,
            "positionY": 84.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "rgba(15, 23, 42, 0.8)", "color": "#F1F5F9", "borderColor": "#334155"}
    },
    {
        "id": "minimal-swiss-mono",
        "name": "Swiss Typo Mono",
        "category": StyleCategory.MINIMAL,
        "description": "Architectural Swiss layout with monospace precision.",
        "tags": ["swiss", "mono", "minimal", "design"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 30,
            "fontWeight": "500",
            "textTransform": "lowercase",
            "textColor": "#F8FAFC",
            "highlightColor": "#38BDF8",
            "strokeColor": "#0F172A",
            "strokeWidth": 1.5,
            "shadowColor": "transparent",
            "positionY": 85.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#0F172A", "color": "#38BDF8", "borderColor": "#0284C7"}
    },
    {
        "id": "minimal-thin-air",
        "name": "Thin Air",
        "category": StyleCategory.MINIMAL,
        "description": "Spacious letter tracking with featherlight aesthetics.",
        "tags": ["thin", "spacious", "aesthetic", "delicate"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 32,
            "fontWeight": "400",
            "letterSpacing": 3.0,
            "textTransform": "uppercase",
            "textColor": "#E2E8F0",
            "highlightColor": "#FFFFFF",
            "strokeColor": "#000000",
            "strokeWidth": 2.0,
            "shadowColor": "rgba(0,0,0,0.5)",
            "shadowBlur": 4.0,
            "positionY": 84.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 100, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#1E293B", "color": "#E2E8F0", "borderColor": "#475569"}
    },
    {
        "id": "minimal-subdued-elegance",
        "name": "Subdued Elegance",
        "category": StyleCategory.MINIMAL,
        "description": "Soft cream serif dialogue font tailored for essays and thought leadership.",
        "tags": ["serif", "elegance", "essay", "thoughtful"],
        "renderSpec": {
            "fontFamily": "Georgia",
            "fontSize": 34,
            "fontWeight": "400",
            "fontStyle": "italic",
            "textTransform": "none",
            "textColor": "#FEF3C7",
            "highlightColor": "#FDE68A",
            "strokeColor": "#1C1917",
            "strokeWidth": 2.0,
            "shadowColor": "rgba(0,0,0,0.5)",
            "shadowBlur": 5.0,
            "positionY": 83.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 110, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#292524", "color": "#FEF3C7", "borderColor": "#78716C"}
    },
    {
        "id": "minimal-nordic-frost",
        "name": "Nordic Frost",
        "category": StyleCategory.MINIMAL,
        "description": "Cool slate and ice tones with clean geometric proportions.",
        "tags": ["nordic", "frost", "cool", "clean"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 32,
            "fontWeight": "500",
            "textTransform": "none",
            "textColor": "#E0E7FF",
            "highlightColor": "#C7D2FE",
            "strokeColor": "#1E1B4B",
            "strokeWidth": 2.0,
            "shadowColor": "rgba(0,0,0,0.5)",
            "shadowBlur": 6.0,
            "positionY": 83.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#1E1B4B", "color": "#E0E7FF", "borderColor": "#4338CA"}
    },
    {
        "id": "minimal-crisp-document",
        "name": "Crisp Document",
        "category": StyleCategory.MINIMAL,
        "description": "Direct, authentic documentarian subtitle style.",
        "tags": ["documentary", "subtitles", "clean"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFFFFF",
            "strokeColor": "#000000",
            "strokeWidth": 3.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 4.0,
            "positionY": 82.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#18181B", "color": "#FFFFFF", "borderColor": "#52525B"}
    },
    {
        "id": "minimal-subtle-grey",
        "name": "Subtle Ash",
        "category": StyleCategory.MINIMAL,
        "description": "Muted gray lower third subtitles that never distract from visuals.",
        "tags": ["subtle", "ash", "lower-third"],
        "renderSpec": {
            "fontFamily": "Tahoma",
            "fontSize": 30,
            "fontWeight": "500",
            "textTransform": "none",
            "textColor": "#CBD5E1",
            "highlightColor": "#F8FAFC",
            "strokeColor": "#0F172A",
            "strokeWidth": 1.5,
            "shadowColor": "rgba(0,0,0,0.5)",
            "shadowBlur": 4.0,
            "positionY": 86.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#0F172A", "color": "#CBD5E1", "borderColor": "#334155"}
    },
    {
        "id": "minimal-obsidian",
        "name": "Obsidian Capsule",
        "category": StyleCategory.MINIMAL,
        "description": "Solid jet-black capsule badge holding clean white subtitles.",
        "tags": ["obsidian", "capsule", "pill", "dark"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 32,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#FFFFFF",
            "highlightColor": "#38BDF8",
            "strokeColor": "transparent",
            "strokeWidth": 0.0,
            "backgroundColor": "rgba(0,0,0,0.85)",
            "backgroundPaddingX": 16.0,
            "backgroundPaddingY": 8.0,
            "backgroundBorderRadius": 20.0,
            "positionY": 82.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#000000", "color": "#38BDF8", "borderColor": "#38BDF8"}
    },
    {
        "id": "minimal-pure-alabaster",
        "name": "Pure Alabaster",
        "category": StyleCategory.MINIMAL,
        "description": "Crisp off-white typography with soft charcoal undertone.",
        "tags": ["alabaster", "pure", "white", "minimal"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#FDFDFD",
            "highlightColor": "#FDFDFD",
            "strokeColor": "#1E293B",
            "strokeWidth": 2.5,
            "shadowColor": "rgba(0,0,0,0.7)",
            "shadowBlur": 6.0,
            "positionY": 83.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#1E293B", "color": "#FDFDFD", "borderColor": "#64748B"}
    },

    # ==================== KINETIC (10) ====================
    {
        "id": "kinetic-word-pop",
        "name": "Pop Kinetic Pro",
        "category": StyleCategory.KINETIC,
        "description": "Dynamic word-by-word pop with 1.25x scale pulse on vocal pronunciation.",
        "tags": ["kinetic", "pop", "pulse", "speech-sync"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 44,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFE600",
            "strokeColor": "#000000",
            "strokeWidth": 6.5,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 8.0,
            "positionY": 75.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.25}
        },
        "thumbnailCss": {"background": "#18181B", "color": "#FFE600", "borderColor": "#FFE600"}
    },
    {
        "id": "kinetic-zoom-flash",
        "name": "Zoom Flash",
        "category": StyleCategory.KINETIC,
        "description": "Energetic rapid zoom-in on stressed syllables.",
        "tags": ["zoom", "flash", "hype"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 46,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFEA00",
            "strokeColor": "#000000",
            "strokeWidth": 7.0,
            "shadowColor": "rgba(0,0,0,0.85)",
            "shadowBlur": 10.0,
            "positionY": 74.0,
            "maxWordsPerLine": 3,
            "displayMode": "chunk",
            "animation": {"type": "zoom", "durationMs": 130, "scale": 1.3}
        },
        "thumbnailCss": {"background": "#172554", "color": "#FFEA00", "borderColor": "#FFEA00"}
    },
    {
        "id": "kinetic-bounce-wave",
        "name": "Bounce Wave",
        "category": StyleCategory.KINETIC,
        "description": "Springy bounce animation adding organic rhythm to spoken phrases.",
        "tags": ["bounce", "spring", "rhythm"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#00FFA3",
            "strokeColor": "#002B1B",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 8.0,
            "positionY": 76.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "bounce", "durationMs": 140, "scale": 1.22}
        },
        "thumbnailCss": {"background": "#022C22", "color": "#00FFA3", "borderColor": "#00FFA3"}
    },
    {
        "id": "kinetic-stomp-impact",
        "name": "Stomp Heavy",
        "category": StyleCategory.KINETIC,
        "description": "Heavy physical stomping effect simulating ground impact.",
        "tags": ["stomp", "heavy", "slam"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 48,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF1744",
            "strokeColor": "#000000",
            "strokeWidth": 8.0,
            "shadowColor": "rgba(0,0,0,0.95)",
            "shadowBlur": 12.0,
            "positionY": 72.0,
            "maxWordsPerLine": 2,
            "displayMode": "chunk",
            "animation": {"type": "elastic", "durationMs": 150, "scale": 1.3}
        },
        "thumbnailCss": {"background": "#3F0314", "color": "#FF1744", "borderColor": "#FF1744"}
    },
    {
        "id": "kinetic-pulse-rhythm",
        "name": "Pulse Rhythm",
        "category": StyleCategory.KINETIC,
        "description": "Continuous subtle heartbeat pulse cadence synchronized to speech.",
        "tags": ["pulse", "heartbeat", "cadence"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 40,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF007F",
            "strokeColor": "#1A000D",
            "strokeWidth": 5.0,
            "shadowColor": "rgba(255,0,127,0.5)",
            "shadowBlur": 12.0,
            "positionY": 77.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "elastic", "durationMs": 115, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#2E0219", "color": "#FF007F", "borderColor": "#FF007F"}
    },
    {
        "id": "kinetic-jitter-glow",
        "name": "Jitter Glow",
        "category": StyleCategory.KINETIC,
        "description": "High-octane energetic jitter with warm radiant glow aura.",
        "tags": ["jitter", "glow", "high-energy"],
        "renderSpec": {
            "fontFamily": "Tahoma",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFB703",
            "strokeColor": "#000000",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(255,183,3,0.7)",
            "shadowBlur": 14.0,
            "positionY": 76.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 105, "scale": 1.18}
        },
        "thumbnailCss": {"background": "#291500", "color": "#FFB703", "borderColor": "#FFB703"}
    },
    {
        "id": "kinetic-dynamic-swell",
        "name": "Dynamic Swell",
        "category": StyleCategory.KINETIC,
        "description": "Gradual swelling growth transition that accentuates speech climax.",
        "tags": ["swell", "growth", "climax"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 44,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF6B6B",
            "strokeColor": "#000000",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 8.0,
            "positionY": 75.0,
            "maxWordsPerLine": 3,
            "displayMode": "chunk",
            "animation": {"type": "zoom", "durationMs": 125, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#300808", "color": "#FF6B6B", "borderColor": "#FF6B6B"}
    },
    {
        "id": "kinetic-flip-in",
        "name": "Flip Perspective",
        "category": StyleCategory.KINETIC,
        "description": "3D perspective flip entry per word segment.",
        "tags": ["flip", "perspective", "3d"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#06D6A0",
            "strokeColor": "#00241A",
            "strokeWidth": 5.5,
            "shadowColor": "rgba(0,0,0,0.85)",
            "shadowBlur": 8.0,
            "positionY": 76.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 120, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#02241C", "color": "#06D6A0", "borderColor": "#06D6A0"}
    },
    {
        "id": "kinetic-slide-up",
        "name": "Slide Float",
        "category": StyleCategory.KINETIC,
        "description": "Smooth vertical slide-in from bottom with buttery deceleration.",
        "tags": ["slide", "vertical", "smooth"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 40,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFD166",
            "strokeColor": "#1A1400",
            "strokeWidth": 5.0,
            "shadowColor": "rgba(0,0,0,0.7)",
            "shadowBlur": 6.0,
            "positionY": 78.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "slide", "durationMs": 130, "scale": 1.1}
        },
        "thumbnailCss": {"background": "#292000", "color": "#FFD166", "borderColor": "#FFD166"}
    },
    {
        "id": "kinetic-pop-surge",
        "name": "Pop Surge",
        "category": StyleCategory.KINETIC,
        "description": "High-intensity scale surge for emphatic words.",
        "tags": ["surge", "pop", "intensity"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 48,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#118AB2",
            "strokeColor": "#000000",
            "strokeWidth": 7.5,
            "shadowColor": "rgba(17,138,178,0.6)",
            "shadowBlur": 12.0,
            "positionY": 72.0,
            "maxWordsPerLine": 2,
            "displayMode": "chunk",
            "animation": {"type": "word-pop", "durationMs": 120, "scale": 1.28}
        },
        "thumbnailCss": {"background": "#05232D", "color": "#118AB2", "borderColor": "#118AB2"}
    },

    # ==================== HIGHLIGHT (10) ====================
    {
        "id": "highlight-karaoke-yellow",
        "name": "Karaoke Sunburst",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Classic karaoke word wipe tracking speech with radiant yellow illumination.",
        "tags": ["karaoke", "yellow", "wipe", "singalong"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 44,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFE600",
            "strokeColor": "#000000",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(0,0,0,0.85)",
            "shadowBlur": 8.0,
            "positionY": 76.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "karaoke", "durationMs": 0, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#1C1917", "color": "#FFE600", "borderColor": "#FFE600"}
    },
    {
        "id": "highlight-boxed-keyword",
        "name": "Crimson Boxed Keyword",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Surrounds the active spoken word with a solid high-visibility crimson badge.",
        "tags": ["boxed", "badge", "crimson", "keyword"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 40,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF0055",
            "secondaryColor": "#FFFFFF",
            "strokeColor": "#000000",
            "strokeWidth": 5.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 8.0,
            "positionY": 77.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 100, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#29000D", "color": "#FF0055", "borderColor": "#FF0055"}
    },
    {
        "id": "highlight-glowing-word",
        "name": "Cyan Glow Aura",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Active words emit a luminous sci-fi cyan aura.",
        "tags": ["cyan", "glow", "aura", "sci-fi"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#E0F2FE",
            "highlightColor": "#00FFFF",
            "strokeColor": "#002733",
            "strokeWidth": 5.0,
            "shadowColor": "rgba(0,255,255,0.8)",
            "shadowBlur": 16.0,
            "positionY": 76.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#002029", "color": "#00FFFF", "borderColor": "#00FFFF"}
    },
    {
        "id": "highlight-neon-marker",
        "name": "Neon Highlighter",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Bold marker stroke illuminating active syllables.",
        "tags": ["marker", "neon", "highlighter"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#CCFF00",
            "strokeColor": "#141A00",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(204,255,0,0.5)",
            "shadowBlur": 12.0,
            "positionY": 76.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "karaoke", "durationMs": 0, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#141A00", "color": "#CCFF00", "borderColor": "#CCFF00"}
    },
    {
        "id": "highlight-invert-focus",
        "name": "Invert Dim Focus",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Dims non-active words to 40% opacity while spotlighting the active word.",
        "tags": ["invert", "dim", "spotlight", "focus"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "rgba(255,255,255,0.45)",
            "highlightColor": "#FFFFFF",
            "strokeColor": "#000000",
            "strokeWidth": 5.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 8.0,
            "positionY": 77.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 100, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#111827", "color": "#FFFFFF", "borderColor": "#9CA3AF"}
    },
    {
        "id": "highlight-dual-tone",
        "name": "Dual Tone Split",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Alternating dual color scheme between active words and contextual sentence.",
        "tags": ["dual-tone", "split", "orange"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 46,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF7A00",
            "secondaryColor": "#00FF88",
            "strokeColor": "#000000",
            "strokeWidth": 7.0,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 10.0,
            "positionY": 74.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#261100", "color": "#FF7A00", "borderColor": "#FF7A00"}
    },
    {
        "id": "highlight-golden-accent",
        "name": "Golden Accent",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Warm golden highlight highlighting narrative authority.",
        "tags": ["gold", "accent", "warm", "narrative"],
        "renderSpec": {
            "fontFamily": "Georgia",
            "fontSize": 38,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FDFBF7",
            "highlightColor": "#E5A93C",
            "strokeColor": "#1A1002",
            "strokeWidth": 4.0,
            "shadowColor": "rgba(0,0,0,0.75)",
            "shadowBlur": 8.0,
            "positionY": 78.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 115, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#1F1403", "color": "#E5A93C", "borderColor": "#E5A93C"}
    },
    {
        "id": "highlight-lime-accent",
        "name": "Acid Lime Accent",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Acid lime punchy active words on clean monochrome body.",
        "tags": ["acid", "lime", "accent", "bold"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 44,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#B8FF00",
            "strokeColor": "#000000",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(0,0,0,0.85)",
            "shadowBlur": 8.0,
            "positionY": 76.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 105, "scale": 1.2}
        },
        "thumbnailCss": {"background": "#172100", "color": "#B8FF00", "borderColor": "#B8FF00"}
    },
    {
        "id": "highlight-fire-word",
        "name": "Blazing Fire",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Intense flame orange highlight with dynamic pop animation.",
        "tags": ["fire", "flame", "orange", "blazing"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 48,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF3D00",
            "strokeColor": "#000000",
            "strokeWidth": 7.5,
            "shadowColor": "rgba(255,61,0,0.6)",
            "shadowBlur": 12.0,
            "positionY": 73.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "bounce", "durationMs": 120, "scale": 1.22}
        },
        "thumbnailCss": {"background": "#290800", "color": "#FF3D00", "borderColor": "#FF3D00"}
    },
    {
        "id": "highlight-underbrush",
        "name": "Royal Purple Brush",
        "category": StyleCategory.HIGHLIGHT,
        "description": "Vibrant royal purple highlight giving a creative boutique flair.",
        "tags": ["purple", "royal", "creative", "boutique"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#8338EC",
            "strokeColor": "#15022C",
            "strokeWidth": 5.5,
            "shadowColor": "rgba(131,56,236,0.6)",
            "shadowBlur": 12.0,
            "positionY": 77.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 115, "scale": 1.18}
        },
        "thumbnailCss": {"background": "#1A0636", "color": "#8338EC", "borderColor": "#8338EC"}
    },

    # ==================== CINEMATIC (10) ====================
    {
        "id": "cinematic-letterbox-classic",
        "name": "Cinema Letterbox Yellow",
        "category": StyleCategory.CINEMATIC,
        "description": "Authentic theatrical dialogue yellow subtitle with crisp black outline.",
        "tags": ["cinema", "theatrical", "yellow", "classic"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#FFEA31",
            "highlightColor": "#FFEA31",
            "strokeColor": "#000000",
            "strokeWidth": 3.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 4.0,
            "positionY": 86.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#000000", "color": "#FFEA31", "borderColor": "#FFEA31"}
    },
    {
        "id": "cinematic-documentary-serif",
        "name": "Documentary Serif",
        "category": StyleCategory.CINEMATIC,
        "description": "High-end BBC/PBS documentary style serif subtitles.",
        "tags": ["documentary", "serif", "bbc", "history"],
        "renderSpec": {
            "fontFamily": "Times New Roman",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#FFFFF0",
            "highlightColor": "#FFFFF0",
            "strokeColor": "#000000",
            "strokeWidth": 2.5,
            "shadowColor": "rgba(0,0,0,0.7)",
            "shadowBlur": 6.0,
            "positionY": 85.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#1A1A1A", "color": "#FFFFF0", "borderColor": "#737373"}
    },
    {
        "id": "cinematic-film-white",
        "name": "35mm Film Print",
        "category": StyleCategory.CINEMATIC,
        "description": "Authentic photochemical 35mm film projected subtitle reproduction.",
        "tags": ["film", "35mm", "print", "celluloid"],
        "renderSpec": {
            "fontFamily": "Georgia",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#EDEDED",
            "highlightColor": "#EDEDED",
            "strokeColor": "#111111",
            "strokeWidth": 2.5,
            "shadowColor": "rgba(0,0,0,0.7)",
            "shadowBlur": 4.0,
            "positionY": 85.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#121212", "color": "#EDEDED", "borderColor": "#525252"}
    },
    {
        "id": "cinematic-criterion-gold",
        "name": "Criterion Gold",
        "category": StyleCategory.CINEMATIC,
        "description": "Signature Criterion Collection aesthetic with soft luminous gold lettering.",
        "tags": ["criterion", "gold", "art-house", "cinema"],
        "renderSpec": {
            "fontFamily": "Georgia",
            "fontSize": 32,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#F4D06F",
            "highlightColor": "#F4D06F",
            "strokeColor": "#1F1600",
            "strokeWidth": 2.5,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 5.0,
            "positionY": 86.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#1A1404", "color": "#F4D06F", "borderColor": "#F4D06F"}
    },
    {
        "id": "cinematic-wide-minimal",
        "name": "Wide Horizon",
        "category": StyleCategory.CINEMATIC,
        "description": "Ultra-wide tracking matching 2.39:1 anamorphic cinematography.",
        "tags": ["anamorphic", "wide", "cinemascope"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 30,
            "fontWeight": "600",
            "letterSpacing": 4.0,
            "textTransform": "uppercase",
            "textColor": "#E5E5E5",
            "highlightColor": "#E5E5E5",
            "strokeColor": "#000000",
            "strokeWidth": 2.0,
            "shadowColor": "rgba(0,0,0,0.6)",
            "shadowBlur": 4.0,
            "positionY": 88.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#000000", "color": "#E5E5E5", "borderColor": "#404040"}
    },
    {
        "id": "cinematic-dramatic-thriller",
        "name": "Thriller Cold",
        "category": StyleCategory.CINEMATIC,
        "description": "Stark contrast white with subtle cold desaturated undertones for thrillers.",
        "tags": ["thriller", "cold", "dramatic", "noir"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 38,
            "fontWeight": "700",
            "textTransform": "uppercase",
            "textColor": "#D8E2DC",
            "highlightColor": "#D8E2DC",
            "strokeColor": "#000000",
            "strokeWidth": 4.0,
            "shadowColor": "rgba(0,0,0,0.85)",
            "shadowBlur": 8.0,
            "positionY": 84.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#0F1416", "color": "#D8E2DC", "borderColor": "#6B7D82"}
    },
    {
        "id": "cinematic-vintage-amber",
        "name": "Vintage 70s Amber",
        "category": StyleCategory.CINEMATIC,
        "description": "Warm nostalgic 1970s sepia amber glow.",
        "tags": ["vintage", "70s", "amber", "nostalgia"],
        "renderSpec": {
            "fontFamily": "Times New Roman",
            "fontSize": 34,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#F3C98B",
            "highlightColor": "#F3C98B",
            "strokeColor": "#291600",
            "strokeWidth": 2.5,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 5.0,
            "positionY": 85.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#291703", "color": "#F3C98B", "borderColor": "#F3C98B"}
    },
    {
        "id": "cinematic-muted-gold",
        "name": "Muted Historical Gold",
        "category": StyleCategory.CINEMATIC,
        "description": "Understated warm brass tones suited for period dramas.",
        "tags": ["historical", "period", "brass", "muted"],
        "renderSpec": {
            "fontFamily": "Georgia",
            "fontSize": 32,
            "fontWeight": "600",
            "textTransform": "none",
            "textColor": "#DDA15E",
            "highlightColor": "#DDA15E",
            "strokeColor": "#211400",
            "strokeWidth": 2.5,
            "shadowColor": "rgba(0,0,0,0.75)",
            "shadowBlur": 6.0,
            "positionY": 85.0,
            "maxWordsPerLine": 6,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#211504", "color": "#DDA15E", "borderColor": "#DDA15E"}
    },
    {
        "id": "cinematic-sci-fi-cyan",
        "name": "Sci-Fi HUD Cyan",
        "category": StyleCategory.CINEMATIC,
        "description": "Futuristic heads-up display subtitle layout.",
        "tags": ["sci-fi", "hud", "cyber", "cyan"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 32,
            "fontWeight": "600",
            "textTransform": "uppercase",
            "textColor": "#A0EADE",
            "highlightColor": "#5CE1E6",
            "strokeColor": "#002428",
            "strokeWidth": 3.0,
            "shadowColor": "rgba(92,225,230,0.5)",
            "shadowBlur": 10.0,
            "positionY": 84.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 100, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#02272E", "color": "#A0EADE", "borderColor": "#5CE1E6"}
    },
    {
        "id": "cinematic-neo-noir",
        "name": "Neo-Noir High Contrast",
        "category": StyleCategory.CINEMATIC,
        "description": "Extreme stark monochrome contrast across horizontal black bars.",
        "tags": ["neo-noir", "monochrome", "stark", "contrast"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 36,
            "fontWeight": "700",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFFFFF",
            "strokeColor": "transparent",
            "strokeWidth": 0.0,
            "backgroundColor": "#000000",
            "backgroundPaddingX": 20.0,
            "backgroundPaddingY": 6.0,
            "backgroundBorderRadius": 0.0,
            "positionY": 85.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "none", "durationMs": 0, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#000000", "color": "#FFFFFF", "borderColor": "#FFFFFF"}
    },

    # ==================== CREATOR_SOCIAL (10) ====================
    {
        "id": "social-tiktok-default",
        "name": "TikTok Classic",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "The quintessential TikTok bold subtitle look with thick border and center punch.",
        "tags": ["tiktok", "viral", "default", "mobile"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 44,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#00F2FE",
            "strokeColor": "#000000",
            "strokeWidth": 6.5,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 6.0,
            "positionY": 75.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.18}
        },
        "thumbnailCss": {"background": "#000000", "color": "#00F2FE", "borderColor": "#00F2FE"}
    },
    {
        "id": "social-reels-gradient",
        "name": "Reels Magenta",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Instagram Reels aesthetic featuring vibrant magenta highlights.",
        "tags": ["reels", "instagram", "magenta", "creator"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 42,
            "fontWeight": "800",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#E1306C",
            "strokeColor": "#000000",
            "strokeWidth": 6.0,
            "shadowColor": "rgba(225,48,108,0.5)",
            "shadowBlur": 10.0,
            "positionY": 76.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "bounce", "durationMs": 120, "scale": 1.18}
        },
        "thumbnailCss": {"background": "#290412", "color": "#E1306C", "borderColor": "#E1306C"}
    },
    {
        "id": "social-yt-shorts-bold",
        "name": "Shorts Retention Master",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Engineered for maximum YouTube Shorts watch-time with high-voltage yellow.",
        "tags": ["shorts", "retention", "yellow", "high-ctr"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 48,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FFCC00",
            "secondaryColor": "#FF0000",
            "strokeColor": "#000000",
            "strokeWidth": 8.0,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 10.0,
            "positionY": 72.0,
            "maxWordsPerLine": 2,
            "displayMode": "chunk",
            "animation": {"type": "word-pop", "durationMs": 100, "scale": 1.25}
        },
        "thumbnailCss": {"background": "#2B2200", "color": "#FFCC00", "borderColor": "#FFCC00"}
    },
    {
        "id": "social-podcast-split",
        "name": "Podcast Dialogue",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Balanced two-line view optimized for long-form clips and podcast interviews.",
        "tags": ["podcast", "interview", "conversation", "dialogue"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 36,
            "fontWeight": "700",
            "textTransform": "none",
            "textColor": "#F8FAFC",
            "highlightColor": "#38BDF8",
            "strokeColor": "#0F172A",
            "strokeWidth": 4.0,
            "shadowColor": "rgba(0,0,0,0.8)",
            "shadowBlur": 6.0,
            "positionY": 78.0,
            "maxWordsPerLine": 5,
            "maxLines": 2,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.12}
        },
        "thumbnailCss": {"background": "#0F172A", "color": "#38BDF8", "borderColor": "#38BDF8"}
    },
    {
        "id": "social-story-caption",
        "name": "Story Aesthetic Pill",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Elegant rounded dark container mimicking premium Instagram stories.",
        "tags": ["story", "instagram", "pill", "aesthetic"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 34,
            "fontWeight": "700",
            "textTransform": "none",
            "textColor": "#FFFFFF",
            "highlightColor": "#F472B6",
            "strokeColor": "transparent",
            "strokeWidth": 0.0,
            "backgroundColor": "rgba(30,41,59,0.85)",
            "backgroundPaddingX": 18.0,
            "backgroundPaddingY": 8.0,
            "backgroundBorderRadius": 14.0,
            "positionY": 80.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 100, "scale": 1.0}
        },
        "thumbnailCss": {"background": "rgba(30,41,59,0.9)", "color": "#F472B6", "borderColor": "#F472B6"}
    },
    {
        "id": "social-gamer-glitch",
        "name": "Gamer Neon Grid",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "High-adrenaline gamer stream aesthetics with electric violet and acid green.",
        "tags": ["gamer", "streamer", "twitch", "neon"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 46,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#00FF66",
            "secondaryColor": "#9900FF",
            "strokeColor": "#1A0033",
            "strokeWidth": 7.0,
            "shadowColor": "rgba(0,255,102,0.6)",
            "shadowBlur": 14.0,
            "positionY": 74.0,
            "maxWordsPerLine": 3,
            "displayMode": "segment",
            "animation": {"type": "elastic", "durationMs": 130, "scale": 1.22}
        },
        "thumbnailCss": {"background": "#1A0033", "color": "#00FF66", "borderColor": "#00FF66"}
    },
    {
        "id": "social-tech-reviewer",
        "name": "Tech Breakdown",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Crisp technical reviewer styling with subtle blue accent.",
        "tags": ["tech", "unboxing", "gadgets", "clean"],
        "renderSpec": {
            "fontFamily": "Segoe UI",
            "fontSize": 36,
            "fontWeight": "600",
            "textTransform": "uppercase",
            "textColor": "#F1F5F9",
            "highlightColor": "#60A5FA",
            "strokeColor": "#020617",
            "strokeWidth": 3.5,
            "shadowColor": "rgba(0,0,0,0.7)",
            "shadowBlur": 6.0,
            "positionY": 80.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "fade", "durationMs": 90, "scale": 1.0}
        },
        "thumbnailCss": {"background": "#020617", "color": "#60A5FA", "borderColor": "#60A5FA"}
    },
    {
        "id": "social-clean-vlogger",
        "name": "Warm Vlogger",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Friendly, welcoming lifestyle vlog typography with warm sunset highlight.",
        "tags": ["vlog", "lifestyle", "warm", "friendly"],
        "renderSpec": {
            "fontFamily": "Trebuchet MS",
            "fontSize": 38,
            "fontWeight": "700",
            "textTransform": "none",
            "textColor": "#FFFFFF",
            "highlightColor": "#F4A261",
            "strokeColor": "#261505",
            "strokeWidth": 4.0,
            "shadowColor": "rgba(0,0,0,0.6)",
            "shadowBlur": 6.0,
            "positionY": 80.0,
            "maxWordsPerLine": 4,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.14}
        },
        "thumbnailCss": {"background": "#261405", "color": "#F4A261", "borderColor": "#F4A261"}
    },
    {
        "id": "social-fitness-coach",
        "name": "Fitness Energy Blast",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Athletic, high-intensity orange lettering inspiring movement.",
        "tags": ["fitness", "gym", "athletic", "energy"],
        "renderSpec": {
            "fontFamily": "Impact",
            "fontSize": 48,
            "fontWeight": "900",
            "textTransform": "uppercase",
            "textColor": "#FFFFFF",
            "highlightColor": "#FF5400",
            "strokeColor": "#000000",
            "strokeWidth": 7.5,
            "shadowColor": "rgba(0,0,0,0.9)",
            "shadowBlur": 10.0,
            "positionY": 72.0,
            "maxWordsPerLine": 3,
            "displayMode": "chunk",
            "animation": {"type": "bounce", "durationMs": 130, "scale": 1.25}
        },
        "thumbnailCss": {"background": "#331100", "color": "#FF5400", "borderColor": "#FF5400"}
    },
    {
        "id": "social-educational-marker",
        "name": "Educator Cyan Marker",
        "category": StyleCategory.CREATOR_SOCIAL,
        "description": "Clear educational whiteboard captions with vivid marker underline.",
        "tags": ["education", "teaching", "whiteboard", "learn"],
        "renderSpec": {
            "fontFamily": "Arial",
            "fontSize": 38,
            "fontWeight": "700",
            "textTransform": "none",
            "textColor": "#FFFFFF",
            "highlightColor": "#00B4D8",
            "strokeColor": "#002029",
            "strokeWidth": 4.5,
            "shadowColor": "rgba(0,0,0,0.7)",
            "shadowBlur": 6.0,
            "positionY": 78.0,
            "maxWordsPerLine": 5,
            "displayMode": "segment",
            "animation": {"type": "word-pop", "durationMs": 110, "scale": 1.15}
        },
        "thumbnailCss": {"background": "#001D24", "color": "#00B4D8", "borderColor": "#00B4D8"}
    }
]


def generate_all():
    target_dir = Path("data/templates")
    target_dir.mkdir(parents=True, exist_ok=True)

    count = 0
    categories = {}

    for t_data in TEMPLATES:
        # Validate through Pydantic
        item = StyleTemplate(**t_data)
        filename = f"{item.id}.json"
        out_file = target_dir / filename
        with open(out_file, "w", encoding="utf-8") as f:
            f.write(json.dumps(item.model_dump(), indent=2))
        count += 1
        cat_str = item.category.value
        categories[cat_str] = categories.get(cat_str, 0) + 1

    print(f"Successfully generated {count} style templates in {target_dir.resolve()}:")
    for cat, num in categories.items():
        print(f"  - {cat}: {num} templates")


if __name__ == "__main__":
    generate_all()

