import math
from typing import List, Optional
from apps.api.app.schemas.render_spec import CaptionRenderSpec, CaptionDisplayMode, CaptionAnimationType
from apps.api.app.services.fonts.font_manager import font_manager


def format_ass_time(seconds: float) -> str:
    """
    Converts floating point seconds to ASS timestamp format: H:MM:SS.cs
    e.g. 65.432 -> 0:01:05.43
    """
    total_cs = int(round(max(0.0, seconds) * 100))
    cs = total_cs % 100
    total_sec = total_cs // 100
    sec = total_sec % 60
    total_min = total_sec // 60
    min_val = total_min % 60
    hour = total_min // 60
    return f"{hour}:{min_val:02d}:{sec:02d}.{cs:02d}"


class ASSRenderer:
    """
    High-fidelity ASS (Advanced SubStation Alpha) v4.00+ generator.
    Produces subtitles with strict visual and timing parity to the CaptionRenderSpec.
    """

    def generate_ass(
        self,
        segments: List[dict],
        spec: CaptionRenderSpec,
        video_width: int = 1920,
        video_height: int = 1080,
        title: str = "CaptionStudio ASS Subtitles",
    ) -> str:
        vw = max(320, video_width or 1920)
        vh = max(240, video_height or 1080)
        scale_factor = vh / 1080.0

        resolved_font = font_manager.resolve_font_name(spec.fontFamily)
        scaled_font_size = max(12, int(round(spec.fontSize * scale_factor)))
        scaled_outline = round(spec.strokeWidth * scale_factor, 1)
        scaled_shadow = round(spec.shadowBlur * 0.4 * scale_factor, 1)

        primary_color = spec.to_ass_color(spec.textColor, default_bgr="FFFFFF", default_alpha="00")
        highlight_color = spec.to_ass_color(spec.highlightColor, default_bgr="00E6FF", default_alpha="00")
        outline_color = spec.to_ass_color(spec.strokeColor, default_bgr="000000", default_alpha="00")
        shadow_color = spec.to_ass_color(spec.shadowColor, default_bgr="000000", default_alpha="60")

        is_bold = -1 if (str(spec.fontWeight) in ("700", "800", "900", "bold", "extrabold", "black")) else 0
        is_italic = -1 if spec.fontStyle == "italic" else 0
        border_style = 3 if (spec.backgroundColor and spec.backgroundColor != "transparent") else 1

        # Position coordinates
        target_x = int(round(vw * (spec.positionX / 100.0)))
        target_y = int(round(vh * (spec.positionY / 100.0)))

        lines = [
            "[Script Info]",
            f"; Script generated by CaptionStudio Phase 2",
            f"Title: {title}",
            "ScriptType: v4.00+",
            "WrapStyle: 0",
            "ScaledBorderAndShadow: yes",
            f"PlayResX: {vw}",
            f"PlayResY: {vh}",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            f"Style: Default,{resolved_font},{scaled_font_size},{primary_color},{highlight_color},{outline_color},{shadow_color},{is_bold},{is_italic},0,0,100,100,{int(spec.letterSpacing)},0,{border_style},{scaled_outline},{scaled_shadow},5,10,10,10,1",
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ]

        def apply_casing(text: str) -> str:
            if spec.textTransform == "uppercase":
                return text.upper()
            elif spec.textTransform == "lowercase":
                return text.lower()
            elif spec.textTransform == "capitalize":
                return text.title()
            return text

        # Alignment tag and position override
        pos_tag = f"{{\\an5\\pos({target_x},{target_y})}}"

        # Generate Dialogue events
        for seg in segments:
            seg_start = seg.get("start_time", seg.get("start", 0.0))
            seg_end = seg.get("end_time", seg.get("end", 0.0))
            seg_text = seg.get("text", "")
            words = seg.get("words", [])

            if seg_end <= seg_start:
                continue

            # Mode 1: Single Word Mode
            if spec.displayMode == CaptionDisplayMode.WORD and words:
                for w in words:
                    w_start = w.get("start_time", w.get("start", seg_start))
                    w_end = w.get("end_time", w.get("end", seg_end))
                    w_text = apply_casing(w.get("word", w.get("text", "")).strip())
                    if w_end > w_start and w_text:
                        pop_anim = "{\\fscx115\\fscy115\\t(0,80,\\fscx100\\fscy100)}" if spec.animation.type == CaptionAnimationType.WORD_POP else ""
                        color_override = f"{{\\c{highlight_color}}}"
                        dialogue = f"Dialogue: 0,{format_ass_time(w_start)},{format_ass_time(w_end)},Default,,0,0,0,,{pos_tag}{pop_anim}{color_override}{w_text}"
                        lines.append(dialogue)
                continue

            # Mode 2: Karaoke timing tags
            if spec.animation.type == CaptionAnimationType.KARAOKE and words:
                k_parts = []
                for w in words:
                    w_start = w.get("start_time", w.get("start", seg_start))
                    w_end = w.get("end_time", w.get("end", seg_end))
                    w_dur_cs = max(1, int(round((w_end - w_start) * 100)))
                    w_text = apply_casing(w.get("word", w.get("text", "")).strip())
                    k_parts.append(f"{{\\k{w_dur_cs}}}{w_text} ")
                dialogue = f"Dialogue: 0,{format_ass_time(seg_start)},{format_ass_time(seg_end)},Default,,0,0,0,,{pos_tag}{''.join(k_parts).strip()}"
                lines.append(dialogue)
                continue

            # Mode 3: Active Word Highlighting with Word Pop or Bounce (Time-sliced events for 100% video parity)
            if words and spec.animation.type in (CaptionAnimationType.WORD_POP, CaptionAnimationType.BOUNCE, CaptionAnimationType.ZOOM, CaptionAnimationType.ELASTIC, CaptionAnimationType.FADE):
                # Ensure words are chronologically ordered
                sorted_words = sorted(words, key=lambda w: w.get("start_time", w.get("start", 0.0)))
                for i, active_word in enumerate(sorted_words):
                    w_start = active_word.get("start_time", active_word.get("start", seg_start))
                    w_end = active_word.get("end_time", active_word.get("end", seg_end))
                    if w_end <= w_start:
                        continue

                    rendered_words = []
                    for j, w in enumerate(sorted_words):
                        w_text = apply_casing(w.get("word", w.get("text", "")).strip())
                        if i == j:
                            # Active word highlighted with animation scale
                            scale_val = int(round(spec.animation.scale * 100))
                            anim_tag = f"{{\\c{highlight_color}\\fscx{scale_val}\\fscy{scale_val}\\t(0,80,\\fscx100\\fscy100)}}"
                            reset_tag = f"{{\\c{primary_color}\\fscx100\\fscy100}}"
                            rendered_words.append(f"{anim_tag}{w_text}{reset_tag}")
                        else:
                            rendered_words.append(w_text)

                    dialogue = f"Dialogue: 0,{format_ass_time(w_start)},{format_ass_time(w_end)},Default,,0,0,0,,{pos_tag}{' '.join(rendered_words)}"
                    lines.append(dialogue)
                continue

            # Mode 4: Static / Simple Segment
            clean_text = apply_casing(seg_text.strip())
            dialogue = f"Dialogue: 0,{format_ass_time(seg_start)},{format_ass_time(seg_end)},Default,,0,0,0,,{pos_tag}{clean_text}"
            lines.append(dialogue)

        return "\n".join(lines) + "\n"


ass_renderer = ASSRenderer()

